load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "prediction",
    srcs = ["checkpoint_evaluator.go"],
    importpath = "github.com/cdsap/build-process-watcher/backend/internal/prediction",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/models",
        "//pkg/predictor",
    ],
)

go_test(
    name = "prediction_test",
    srcs = ["checkpoint_evaluator_test.go"],
    embed = [":prediction"],
    deps = [
        "//internal/models",
        "//pkg/predictor",
    ],
)
