name: "Build Process Watcher"
description: "Tracks memory usage of build processes during the job"

inputs:
  interval:
    description: "Polling interval in seconds"
    required: false
    default: "5"

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/cleanup.js"

# Optional if you're publishing this to the Marketplace
branding:
  icon: "activity"
  color: "gray-dark"