load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "predictor",
    srcs = [
        "predictor.go",
        "remote.go",
    ],
    importpath = "github.com/cdsap/build-process-watcher/backend/pkg/predictor",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "@org_golang_google_api//idtoken",
    ],
)

go_test(
    name = "predictor_test",
    srcs = [
        "predictor_test.go",
        "remote_test.go",
    ],
    embed = [":predictor"],
)
