load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "scoring",
    srcs = ["errors.go"],
    importpath = "github.com/cdsap/build-process-watcher/backend/internal/scoring",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "scoring_test",
    srcs = ["errors_test.go"],
    embed = [":scoring"],
)
